services:
  web:
    restart: unless-stopped
    build:
      context: ./web-react
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:80"
    depends_on:
      - api

  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8010:8000"

  bot:
    restart: unless-stopped
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_BASE_URL: http://api:8000/api
    depends_on:
      - api
